
###
GET  http://localhost:4000/api/employees
###
POST  http://localhost:4000/api/employees
Content-Type: application/json

{
    "name": "Mario Roberto",
    "position": "Developer",
    "office": "Home",
    "salary": "20000"
}
###
GET  http://localhost:4000/api/employees/6165c2fde05cc734ea2eb359